### AVR executable Makefile for Posix

PROGRAMMER = -cusbtiny
#PROGRAMMER = -cstk500v1 -P/dev/tty.usbmodem34521
#NO_CORELIB = true
OPTIMIZE = 3
#LIBS 	= -lTinyDebugSerial
#INC	= -I ../lib/TinyDebugSerial

F_CPU 	= 8000000L
MCU	= attiny85

LFUSE	= 0xE2
HFUSE	= 0xDF
EFUSE 	= 0xFF

include ../base.mk